version: 2
models:
  - name: marts_d_clientes
    description: "{{ doc('marts_d_clientes') }}"
    columns:
      - name: cliente_id
        description: "Identificador único do cliente."
        data_tests:
          - not_null
          - unique
      - name: nome
        description: "Nome completo do cliente."
      - name: estado_civil
        description: "Estado civil do cliente em formato descritivo."
      - name: genero
        description: "Gênero do cliente em formato descritivo."
      - name: estado
        description: "Estado ou província associado ao cliente."
      - name: pais_regiao
        description: "País ou região associado ao cliente."
  - name: marts_d_date
    description: "{{ doc('marts_d_date') }}"
    columns:
      - name: data_id
        description: "Identificador único da data."
        data_tests:
          - not_null
          - unique
      - name: data
        description: "Data completa correspondente ao registro."
        data_tests:
          - not_null
      - name: mes_nome
        description: "Nome do mês em inglês."
      - name: mes
        description: "Número do mês."
      - name: ano
        description: "Ano do calendário."
        data_tests:
          - not_null
          - accepted_values:
              arguments:
                values: [2013, 2014]
  - name: marts_d_produtos
    description: "{{ doc('marts_d_produtos') }}"
    columns:
      - name: produto_id
        description: "Identificador único do produto."
        data_tests:
          - not_null
          - unique
      - name: produto
        description: "Nome comercial do produto."
        data_tests:
          - not_null
      - name: modelo
        description: "Nome do modelo do produto."
      - name: subcategoria
        description: "Nome da subcategoria do produto."
        data_tests:
          - not_null
      - name: categoria
        description: "Nome da categoria do produto."
        data_tests:
          - not_null

  - name: marts_f_vendas
    description: "{{ doc('marts_f_vendas') }}"
    columns:
      - name: venda_id
        description: >
          Identificador do pedido de venda.
          Um mesmo pedido pode possuir múltiplas linhas de produtos.
        data_tests:
          - not_null
      - name: data_id
        description: "Identificador da data do pedido."
        data_tests:
          - not_null
          - relationships:
              arguments:
                to: ref('stg_dim_date')
                field: data_id
      - name: produto_id
        description: "Identificador do produto vendido."
        data_tests:
          - not_null
          - relationships:
              arguments:
                to: ref('stg_dim_product')
                field: produto_id
      - name: cliente_id
        description: "Identificador do cliente associado à venda."
        data_tests:
          - not_null
          - relationships:
              arguments:
                to: ref('stg_dim_customer')
                field: cliente_id
      - name: receita
        description: "Valor total da receita gerada pela venda."
        data_tests:
          - not_null
      - name: custo_produto
        description: >
          Custo total dos produtos vendidos, calculado através
          do custo padrão unitário multiplicado pela quantidade.
        data_tests:
          - not_null
      - name: frete
        description: "Valor do frete associado à venda."
        data_tests:
          - not_null
      - name: imposto
        description: "Valor do imposto associado à venda."
        data_tests:
          - not_null
      - name: lucro_bruto
        description: >
          Resultado obtido pela diferença entre a receita da venda
          e o custo dos produtos vendidos.
        data_tests:
          - not_null
      - name: lucro_apos_frete_imposto
        description: >
          Resultado obtido após a dedução do custo dos produtos,
          frete e impostos da receita da venda.
        data_tests:
          - not_null
      - name: quantidade
        description: "Quantidade de produtos vendidos."
        data_tests:
          - not_null