name: 'dbt_adventureworks2022'
version: '1.0.0'

# Perfil utilizado para conexão com o banco de dados
profile: 'dbt_adventureworks2022'

# Caminhos do projeto
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
docs-paths: ["models/docs"]



# Diretórios removidos pelo comando dbt clean
clean-targets:
  - "target"
  - "dbt_packages"

# Configuração dos modelos
models:
  dbt_adventureworks2022:
    +docs:
      node_color: "#4CAF50"
    staging:
      +materialized: view
      +schema: staging
    # Camada analítica final
    marts:
      +materialized: table
      +schema: marts
      
      